# Generated by Django 4.2.6 on 2023-11-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_pay_tb'),
        ('seller', '0002_rename_file_seller_tb_file_product_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Time', models.CharField(max_length=20)),
                ('Details', models.CharField(max_length=20)),
                ('Orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.order_tb')),
            ],
        ),
    ]
