# Generated by Django 4.2.6 on 2023-10-31 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_order_tb_orderitems_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tb',
            name='OrderDate',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tb',
            name='OrderTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
